### ISSUE TITLE
Incorrect handling of CDN Css File

### ISSUE THREAD

**Issue by brucealdridge** [yiisoft/app#126]
### What steps will reproduce the problem?

```
composer create-project --prefer-dist --stability=dev yiisoft/app
composer run serve 
```

### What is the expected result?

Fontawesome icons included

### What do you get instead?

~~~
<link href="/https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
~~~

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev-master
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
https://github.com/yiisoft/assets/issues/53

**Comment by samdark** [comment]
Should be fixed now.
