### ISSUE TITLE
Composer installation error

### ISSUE THREAD

**Issue by huguoliang** [yiisoft/app#153]
/var/www$ composer create-project --prefer-dist --stability=dev yiisoft/app app
Creating a "yiisoft/app" project at "./app"
Installing yiisoft/app (1.0.x-dev 9b4ba451eb7a4d2ea1b0d17cc53849b66920b3da)
  - Downloading yiisoft/app (dev-master 9b4ba45)
  - Installing yiisoft/app (dev-master 9b4ba45): Extracting archive
Created project in /var/www/app
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yiisoft/files ^1.0 -> satisfiable by yiisoft/files[1.0.0].
    - yiisoft/yii-view dev-master requires yiisoft/csrf ^1.0 -> satisfiable by yiisoft/csrf[1.0.0, 1.0.1, 1.0.2].
    - yiisoft/csrf[1.0.0, ..., 1.0.2] require yiisoft/security ^1.0 -> satisfiable by yiisoft/security[1.0.0].
    - yiisoft/security 1.0.0 requires yiisoft/strings ^1.0 -> satisfiable by yiisoft/strings[1.0.0, 1.0.1, 1.1.0, 1.2.0].
    - You can only install one version of a package, so only one of these can be installed: yiisoft/strings[1.0.0, 1.0.1, 1.1.0, 1.2.0, 2.0.0].
    - yiisoft/yii-view 3.0.x-dev is an alias of yiisoft/yii-view dev-master and thus requires it to be installed too.
    - yiisoft/files 1.0.0 requires yiisoft/strings ^2.0 -> satisfiable by yiisoft/strings[2.0.0].
    - Root composer.json requires yiisoft/yii-view ^3.0@dev -> satisfiable by yiisoft/yii-view[3.0.x-dev (alias of dev-master)].

**Comment by samdark** [comment]
Likely you were trying to update during big config adjustments. This is done by now. I've tried your command and it works now.

**Comment by razonyang** [comment]
@huguoliang I had the same problem while using Alibaba's packagist mirror. It works after switching back to packagist.
