### ISSUE TITLE
Serving app from localhost results in 404

### ISSUE THREAD

**Issue by axtho** [yiisoft/app#215]
### What steps will reproduce the problem?
Install the app via composer as documented in the readme or the guide.
`composer run serve` works.

### What is the expected result?
When pointing the browser to `localhost/app/public/` I would expect the same result as running the app through the build in server.

### What do you get instead?
I get a 404 page for the base path (localhost/app/public/)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | latest
| PHP version      |  8.0.3 (MAMP Setup, .htaccess works on other projects)
| Operating system | OS X

**Comment by samdark** [comment]
Check https://github.com/yiisoft/yii-middleware/blob/master/src/SubFolder.php
