### ISSUE TITLE
route Group exception

### ISSUE THREAD

**Issue by fufudao** [yiisoft/app#239]
Exception:   Route should be either an instance of Route or Group, array given.

### What steps will reproduce the problem?
change of the file  app/config/routes.php:

```php
declare(strict_types=1);

use App\Controller\SiteController;
use Yiisoft\Router\Route;
use \Yiisoft\Router\Group;

return [
    Route::get('/')->action([SiteController::class, 'index'])->name('home'),
    **Group::create('/api')
    ->middleware(ApiAuthentication::class)
    ->host('https://example.com')
    ->routes([
        Route::get('/comments'),
    ])**
];
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version     8 | 
| Operating system |

**Comment by vjik** [comment]
Use method `routes` without array:

```php
return [
    Route::get('/')->action([SiteController::class, 'index'])->name('home'),
    Group::create('/api')
        ->middleware(ApiAuthentication::class)
        ->host('https://example.com')
        ->routes(
            Route::get('/comments'),
        )
];
```

**Comment by fufudao** [comment]
`<?php

declare(strict_types=1);

use App\Controller\SiteController;
use Yiisoft\Router\Route;
use \Yiisoft\Router\Group;

return [
    Route::get('/')->action([SiteController::class, 'index'])->name('home'),
    Group::create('/api')
    ->middleware(ApiAuthentication::class)
    ->host('https://example.com')
    ->routes([
        Route::get('/comments'),
    ])
];

github delete []`
