### ISSUE TITLE
Asset manager ended with an error

### ISSUE THREAD

**Issue by ljfreelancer88** [yiisoft/app#26]
Hi, when I installed Yii3. I got `Asset manager ended with an error`. The vendor folder doesn't even created.

![Screenshot from 2020-07-10 14-50-50](https://user-images.githubusercontent.com/7919039/87188566-0d8a5b00-c2bd-11ea-9c24-dd42986b27f4.png)

| PHP version  |  7.4
| Operating system | ubuntu 20.04

**Comment by terabytesoftw** [comment]
Could you describe the steps you are taking to reproduce the error, I just tested the installation and it works fine, what version of php exactly, version of composer.
