### ISSUE TITLE
yii serve Error Code 127

### ISSUE THREAD

**Issue by push32** [yiisoft/app#27]
i'm follow the readme.md and tried to test the yii3 and when i'm use "composer run server" show error

```
> yii serve
sh: yii: command not found
Script yii serve handling the serve event returned with error code 127
```

**Comment by samdark** [comment]
That should be `./vendor/bin/yii serve`.

**Comment by push32** [comment]
when i'm using this command

`composer create-project --prefer-dist --stability=dev yiisoft/app <your project>`

and tried to running

`composer run serve`

its show 

```
> yii serve
sh: yii: command not found
Script yii serve handling the serve event returned with error code 127
```

and i'm looking into the `./vendor/bin/` it's empty

hope this information helpful

**Comment by samdark** [comment]
Seems your composer installation did not go well. I guess, because of https://github.com/yiisoft/app/issues/28.

It should be:

```
λ composer run serve
> yii serve
[Mon Jul 13 13:43:33 2020] PHP 7.4.3 Development Server (http://localhost:8080) started
Server started on http://localhost:8080/
Document root is "C:\src\delete_me\yii3start/public"
Quit the server with CTRL-C or COMMAND-C.
```

That's what I get locally.

**Comment by Tarekajaj** [comment]
the issue appears on macos, to fix it in composer.json update the line `"serve": "yii serve",` to `"serve": "./yii serve",` to make it work
