### ISSUE TITLE
Configuration group naming conventions and adjustments

### ISSUE THREAD

**Issue by samdark** [yiisoft/app#271]
> ℹ️ Note that this is not about configuration file names. It is about [config groups](https://github.com/yiisoft/config/blob/master/README.md#config-groups).

## Problem

- Names do not show what is container config and what are params.
- There is no naming convention defined.

## Solution

1. Accept/merge "022 - Config groups":
- [x] https://github.com/yiisoft/docs/pull/180

2. Adjust runners:
  - [x] https://github.com/yiisoft/yii-runner/pull/39
  - [x] https://github.com/yiisoft/yii-runner-console/pull/34
  - [x] https://github.com/yiisoft/yii-runner-http/pull/43
  - [x] https://github.com/yiisoft/yii-runner-roadrunner/pull/52

3. Adapt packages to new runners
 - [x] https://github.com/yiisoft/yii-testing/pull/22

4. Adjust group names in existing packages providing configs:
  - `common` → `di`
  - `web` → `di-web`
  - `console` → `di-console`
  - `providers` → `di-providers`
  - `providers-web` → `di-providers-web`
  - `providers-console` → `di-providers-console`
  - `delegates` → `di-delegates`
  - `delegates-web` → `di-delegates-web`
  - `delegates-console` → `di-delegates-console`
  - `tags` → `di-tags`
  - `tags-web` → `di-tags-web` 
  - `tags-console` → `di-tags-console`
  
4.1. Create and merge adapt PRs in released packages:
- [x] https://github.com/yiisoft/assets/pull/115
- [x] https://github.com/yiisoft/aliases/pull/59
- [x] https://github.com/yiisoft/auth-jwt/pull/59
- [x] https://github.com/yiisoft/cache-file/pull/56
- [x] https://github.com/yiisoft/cache-memcached/pull/45
- [x] https://github.com/yiisoft/cache/pull/117
- [x] https://github.com/yiisoft/csrf/pull/43
- [x] https://github.com/yiisoft/data-response/pull/71
- [x] https://github.com/yiisoft/error-handler/pull/72
- [x] https://github.com/yiisoft/log-target-email/pull/41
- [x] https://github.com/yiisoft/log-target-file/pull/53
- [x] https://github.com/yiisoft/log-target-syslog/pull/32
- [x] yiisoft/log (not need)
- [x] https://github.com/yiisoft/mailer-symfony/pull/27
- [x] https://github.com/yiisoft/profiler/pull/64
- [x] https://github.com/yiisoft/rbac-rules-container/pull/25
- [x] https://github.com/yiisoft/router-fastroute/pull/122
- [x] https://github.com/yiisoft/router/pull/187
- [x] https://github.com/yiisoft/session/pull/47
- [x] https://github.com/yiisoft/translator-extractor/pull/31
- [x] https://github.com/yiisoft/translator/pull/111
- [x] https://github.com/yiisoft/user/pull/67
- [x] https://github.com/yiisoft/view-twig/pull/53
- [x] https://github.com/yiisoft/view/pull/219
- [x] yiisoft/widget (not need)
- [x] yiisoft/yii-bulma (not need)
- [x] https://github.com/yiisoft/yii-console/pull/171
- [x] https://github.com/yiisoft/yii-event/pull/50
- [x] https://github.com/yiisoft/yii-sentry/pull/25
- [x] https://github.com/yiisoft/yii-swagger/pull/69
- [x] https://github.com/yiisoft/yii-view/pull/72

4.2. Create and merge adapt PRs in non-released packages:

- [x] https://github.com/yiisoft/yii-auth-client/pull/50
- [x] https://github.com/yiisoft/yii-gii/pull/82
- [x] https://github.com/yiisoft/yii-debug/pull/191
- [x] https://github.com/yiisoft/db-sphinx/pull/38
- [x] https://github.com/yiisoft/yii-dataview/pull/113
- [x] https://github.com/yiisoft/yii-queue/pull/144
- [x] yiisoft/log-target-db (not need)
- [x] https://github.com/yiisoft/validator/pull/554
- [x] https://github.com/yiisoft/yii-db-migration/pull/147
- [x] yiisoft/cache-db (not need)
- [x] https://github.com/yiisoft/yii-cycle/pull/155
- [x] https://github.com/yiisoft/yii-debug-api/pull/91
- [x] yiisoft/yii-filesystem (deprecated)
- [x] yiisoft/form (not need)
- [x] yiisoft/yii-bootstrap5 (not need)
- [x] https://github.com/yiisoft/yii-queue-amqp/pull/54
- [x] https://github.com/yiisoft/translator-message-db/pull/47
- [x] https://github.com/yiisoft/yii-debug-viewer/pull/57
- [x] https://github.com/yiisoft/yii-testing/pull/24

4.3. Make releases:

- [x] https://github.com/yiisoft/assets/
- [x] https://github.com/yiisoft/aliases/
- [x] https://github.com/yiisoft/auth-jwt/
- [x] https://github.com/yiisoft/cache-file/
- [x] https://github.com/yiisoft/cache-memcached/
- [x] https://github.com/yiisoft/cache/
- [x] https://github.com/yiisoft/csrf/
- [x] https://github.com/yiisoft/data-response/
- [x] https://github.com/yiisoft/error-handler/
- [x] https://github.com/yiisoft/log-target-email/
- [x] https://github.com/yiisoft/log-target-file/
- [x] https://github.com/yiisoft/log-target-syslog/
- [x] yiisoft/log (not need)
- [x] https://github.com/yiisoft/mailer-symfony/
- [x] https://github.com/yiisoft/profiler/
- [x] https://github.com/yiisoft/rbac-rules-container/
- [x] https://github.com/yiisoft/router-fastroute/
- [x] https://github.com/yiisoft/router/
- [x] https://github.com/yiisoft/session/
- [x] https://github.com/yiisoft/translator-extractor/
- [x] https://github.com/yiisoft/translator/
- [x] https://github.com/yiisoft/user/
- [x] https://github.com/yiisoft/view-twig/
- [x] https://github.com/yiisoft/view/
- [x] https://github.com/yiisoft/yii-console/
- [x] https://github.com/yiisoft/yii-event/
- [x] https://github.com/yiisoft/yii-sentry/
- [x] https://github.com/yiisoft/yii-swagger/
- [x] https://github.com/yiisoft/yii-view/

5. Adapt application templates:

- [x] https://github.com/yiisoft/app/pull/270
- [x] https://github.com/yiisoft/app-api/pull/159
- [x] https://github.com/yiisoft/app-console/pull/17

6. Adapt demo:

- [x] https://github.com/yiisoft/demo/pull/570

7. Write down short upgrade guides and publish to chats.
- [x] Make upgrade guide: https://gist.github.com/samdark/219245fea45749b60ab679609ad2e64c
- [x] Publish news

**Comment by xepozz** [comment]
Having `container` in file/directory names is worse than without it imho

**Comment by samdark** [comment]
@xepozz updated issue a bit. How about now?

**Comment by xepozz** [comment]
> @xepozz updated issue a bit. How about now? (agreements text is in PR linked)

Awful to be honest

**Comment by vjik** [comment]
Done 🎉
