### ISSUE TITLE
Foxy\Exception\RuntimeException

### ISSUE THREAD

**Issue by push32** [yiisoft/app#28]
When installing using composer, it's shows

` - Installing foxy/foxy (v1.1.0): Loading from cache`
`Plugin installation failed, rolling back`
`  - Removing foxy/foxy (v1.1.0)`

`[Foxy\Exception\RuntimeException]`
`  No asset manager is found`

**Comment by samdark** [comment]
What command do you issue?

**Comment by push32** [comment]
![Screenshot 2020-07-13 at 9 56 55 AM](https://user-images.githubusercontent.com/24914270/87266341-32feab00-c4ef-11ea-85d6-34628c810c3d.png)

when i'm install using the instruction from readme.md it's show this error, i think i should report it
Correct me if i'm wrong

**Comment by samdark** [comment]
I can't reproduce it. Installs flawlessly from readme. What are your PHP version, Composer version, OS?

**Comment by push32** [comment]
PHP Version
PHP 7.4.8 (cli) (built: Jul  9 2020 23:43:51) ( NTS )

Composer Version
Composer version 1.9.2 2020-01-14 16:30:31

OS
MacOS Catalina

I think, i will delete and try to reinstall once again, thank you Mr @samdark
