### ISSUE TITLE
The codecept run requires now .env file and fails in the CI

### ISSUE THREAD

**Issue by alexander-schranz** [yiisoft/app#299]
### What steps will reproduce the problem?

Run codecept without .env file

### What is the expected result?

Allow to run codecept without .env file, specially for CI tasks.

### What do you get instead?

<img width="1280" alt="Bildschirmfoto 2023-07-25 um 00 28 15" src="https://github.com/yiisoft/app/assets/1698337/0d454f8d-f05e-4460-9005-998a3ad4a021">

This did happen after updating dependencies.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.1 / 8.2
| Operating system | MacOS / Ubuntu

**Comment by samdark** [comment]
That's interesting because our build w/ Codeception passes:https://github.com/yiisoft/app/actions/runs/5171349174/job/13992799314
