### ISSUE TITLE
install with composer seems freezed

### ISSUE THREAD

**Issue by paskuale75** [yiisoft/app#31]
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )  | 
| Ubuntu 20.04 |

**Comment by samdark** [comment]
What's your Composer versison?

**Comment by paskuale75** [comment]
it seems to have been momentary, I tried again this morning and it cloned everything.
