### ISSUE TITLE
hello, Can I use Yii to product project?

### ISSUE THREAD

**Issue by wzbmail** [yiisoft/app#324]
### What steps will reproduce the problem?
Hello, everyone. Excuse me, can I use yii3 in the formal product project now?

### What is the expected result?
yes!
### What do you get instead?
no

**Comment by vjik** [comment]
Recommend to use released packages only (see list of packages [here](https://www.yiiframework.com/status/3.0)).

So far, only [console application](https://github.com/yiisoft/app-console) is ready from application templates.
