### ISSUE TITLE
Debug panel not visible

### ISSUE THREAD

**Issue by evil1** [yiisoft/app#48]
### What steps will reproduce the problem?
Clean install with `composer create-project --prefer-dist --stability=dev yiisoft/app <app_name>`
and `composer run serve`
Debugger is enabled in params file
```
    'yiisoft/yii-debug' => [
        'enabled' => true
    ],
```

### What is the expected result?
Access the index page with debugger enabled

### What do you get instead?
No debug panel is visible

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.x-dev
| PHP version      | 7.4.5
| Operating system | Windows 10 x64

**Comment by samdark** [comment]
Yes, it's not ready.

**Comment by evil1** [comment]
@samdark What can I do to make it ready? Where to start?

**Comment by samdark** [comment]
Get to "yii3ru" Telegram chat. We'll guide you.
