### ISSUE TITLE
Move  SessionMiddleware, CsrfMiddleware, ErrorCatcher Middleware to routes

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/app#69]
It is proposed by SessionMiddleware, CsrfMiddleware, ErrorCatcher to transfer [MiddlewareProvider.php](https://github.com/yiisoft/app/blob/592f17b12ed3b9ed5d8fa5e742845f95f228ebb3/src/Provider/MiddlewareProvider.php#L22) to [routes.php](https://github.com/yiisoft/app/blob/master/config/routes.php) since the application can have REST API and other APIs for which these Middleware are not required.

**Comment by samdark** [comment]
These are different ways of registering middleware. Error handler should be application wide in majority of cases while the rest are used like that in the app template. I'll update docs to describe it better.
