### ISSUE TITLE
composer run serve EventDispatcher error

### ISSUE THREAD

**Issue by julianrutten** [yiisoft/app#79]
### What steps will reproduce the problem?
I just ran `composer create-project --prefer-dist --stability=dev yiisoft/app app`
And then `composer run serve`

### What is the expected result?
Start development webserver

### What do you get instead?
```PHP Fatal error:  Uncaught Yiisoft\Factory\Exceptions\NotFoundException: No definition for Psr\EventDispatcher\EventDispatcherInterface in <removed>/vendor/yiisoft/di/src/Container.php:222```

### Additional info
Unsure what about my system setup is wrong here, couldnt find anything regarding this on google or obvious packages I needed to install. What am I missing?

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.11
| Operating system | Ubuntu 20.04

**Comment by julianrutten** [comment]
I fixed this by adding the event-dispatcher provider to `config/providers.php`. However now I am getting 
```GET / - Uncaught Yiisoft\Injector\MissingRequiredArgumentException: Missing required argument "event" when calling "collect" in "/home/julian/yiisoft/app/vendor/yiisoft/yii-debug/src/Collector/WebAppInfoCollector.php" at line 32. in /home/julian/yiisoft/app/vendor/yiisoft/injector/src/Injector.php:147```

Any ideas?

**Comment by Mister-42** [comment]
That last one I (temporarily) 'fixed' by disabling debug.

**Comment by julianrutten** [comment]
Apparently we tried that out at the same time haha, so at least im not the only one with the issue. Guess we will wait for fixes then, you guys can close this if it is a duplicate.

**Comment by samdark** [comment]
Likely is this case: https://github.com/yiisoft/di/pull/185

**Comment by samdark** [comment]
Fixed.
