### ISSUE TITLE
Remove need to rebuild config

### ISSUE THREAD

**Issue by Nex-Otaku** [yiisoft/app#9]
For now, if I add new console command to app, **_I have to rebuild config_**, to apply changes.

Even on development environment!

This behavior is the least expected and VERY surprising.

I must run `composer du` every time I change config... Pain (

**How it should be?**

1. Config caching must be an option.

2. Config caching must be DISABLED by default in development environment.

3. Config with disabled caching must be loaded from disk, fresh every time the app starts.

4. User MUST have a choice to enable or disable config caching at any moment.

5. Option CAN be enabled by default for production environment.

**Comment by samdark** [comment]
How to solve it:

1. Place rebuild in https://github.com/yiisoft/yii-console/blob/master/bin/yii#L42 same as in https://github.com/yiisoft/app/blob/master/public/index.php#L28.
2. Make it configurable via config or environmental variables.

**Comment by samdark** [comment]
Done. Now rebuild happens only if configs were changed.
